-------------------------------------------------------------------------------
Test set: challenge.alkemy.DisneyApplicationTests
-------------------------------------------------------------------------------
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 6.105 s <<< FAILURE! - in challenge.alkemy.DisneyApplicationTests
contextLoads  Time elapsed: 0.001 s  <<< ERROR!
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.AnnotationException: @OneToOne or @ManyToOne on challenge.alkemy.entidades.Genero.imagen references an unknown entity: java.lang.String
Caused by: org.hibernate.AnnotationException: @OneToOne or @ManyToOne on challenge.alkemy.entidades.Genero.imagen references an unknown entity: java.lang.String

